services:
  spark-notebook:
    image: jupyter/pyspark-notebook
    container_name: spark-container
    ports:
      - "8889:8888"   # Jupyter UI (8889 no host → 8888 no container)
      - "4040:4040"   # Spark Web UI
      - "7077:7077"   # Spark master
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
